name: EdgeX-Device-Rest
on:
  schedule:
  - cron:  "0 6 * * *"
jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and version repo
        uses: canonical/edgex-sync-and-create-launchpad-branch-action@v1.3.9
        with:
          edgex-repo: "device-rest-go"
          canonical-repo: "edgex-device-rest-go"
          ssh-private-key: ${{ secrets.SSH_CANONICAL_EDGEX_DEVICE_REST }}  
          patch-file: "0001-snapcraft-version-patch.diff" 
  build-snap:
    runs-on: ubuntu-latest
    needs: sync-repo
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: canonical/device-rest-go
        ref: launchpad
    - name: Build the snap
      uses: snapcore/action-build@v1
    - name: Uploading snap artifact
      uses: actions/upload-artifact@v2
      with:
        name: snap-files
        path: "*.snap"   
    - name: Test the snap
      uses: canonical/edgex-test-device-snap-action@v1.4
      with:
        edgex_device_snap: "edgex-device-rest"
        edgex_service_name: "device-rest-go"
        edgex_device_name: "sample-json" 
  build-launchpad:
    runs-on: ubuntu-latest
    needs:  build-snap
    steps:
      - name: Kick off Launchpad build
        uses: canonical/edgex-launchpad-build-action@v1.4
        with:
          edgex_snap: "edgex-device-rest"
          consumer_name: ${{ secrets.LP_CONSUMER_NAME }}
          access_token: ${{ secrets.LP_ACCESS_TOKEN }}
          access_secret: ${{ secrets.LP_ACCESS_SECRET }}         
