name: EdgeX-device-grove
on: push
#  schedule:
#  - cron:  "0 6 * * *"
jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and version repo
        uses: canonical/edgex-sync-and-create-launchpad-branch-action@v1.4.0
        with:
          edgex-repo: "device-grove-c"
          canonical-repo: "edgex-device-grove-c"
          ssh-private-key: ${{ secrets.SSH_CANONICAL_EDGEX_DEVICE_GROVE }}    
  build-snap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: canonical/device-grove-c
        ref: launchpad
    - name: Build the snap
      uses: snapcore/action-build@v1
    - name: Uploading snap artifact
      uses: actions/upload-artifact@v2
      with:
        name: snap-files
        path: "*.snap"   
    - name: MM Failure
      if: ${{ failure() }}
      run: |
        echo "{\"text\":\":stop-sign: [${{github.event_name}}] ${{github.workflow}} See logs at https://github.com/canonical/edgex-sync/actionsruns/${{github.run_id}} \"}"
        curl -i -X POST -H "{\"text\":\":stop-sign: [${{github.event_name}}] ${{github.workflow}} See logs at https://github.com/canonical/edgex-sync/actionsruns/${{github.run_id}} \"}" ${{secrets.MATTERMOST}}

